# @server = https://luiscarbl-redesigned-lamp-9p44j4p7qj739569-8080.preview.app.github.dev
@server = https://sem8.onrender.com
@apiserver = {{server}}/api/curso
###

GET {{server}}
###



GET {{server}}/codigo
###
GET {{server}}/nombre-completo

###
GET {{apiserver}}/listar

###
POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=Inteligencia+Artificial&creditos=4

###
DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=54


